# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseServiceItemsRecipe
  categories:
  - KitchenNF
  completetime: 1
  materials:
    Steel: 75

# Recipes

- type: latheRecipe
  id: ServiceRollingPin
  result: RollingPin
  parent: BaseServiceItemsRecipe
  materials:
    Wood: 200

- type: latheRecipe
  id: ServiceSpoon
  result: Spoon
  parent: BaseServiceItemsRecipe

- type: latheRecipe
  id: ServiceFork
  result: Fork
  parent: BaseServiceItemsRecipe

- type: latheRecipe
  id: ServicePairedChopsticks
  result: PairedChopsticks
  parent: BaseServiceItemsRecipe
  materials:
    Glass: 100

- type: latheRecipe
  id: NapkinDrum
  result: NapkinDrum
  parent: BaseServiceItemsRecipe
  applyMaterialDiscount: false

- type: latheRecipe
  id: Napkin
  result: Napkin
  parent: BaseServiceItemsRecipe
  completetime: 0.1
  applyMaterialDiscount: false
  materials:
    Paper: 10

- type: latheRecipe
  id: ServiceSelectiveDropper
  result: ServiceSelectiveDropper
  parent: BaseServiceItemsRecipe
  materials:
    Glass: 200
    Plastic: 100
    Steel: 100

- type: latheRecipe
  id: CondimentCupDispenser
  result: CondimentCupDispenser
  parent: BaseServiceItemsRecipe
  applyMaterialDiscount: false

- type: latheRecipe
  id: CondimentCup
  result: CondimentCup
  parent: BaseServiceItemsRecipe
  completetime: 0.1
  applyMaterialDiscount: false
  materials:
    Steel: 10

- type: latheRecipe
  id: FoodCondimentSqueezeBottleClear
  result: FoodCondimentSqueezeBottleClear
  parent: BaseServiceItemsRecipe
  applyMaterialDiscount: false
  materials:
    Plastic: 50

- type: latheRecipe
  id: SodiumLightBulb
  result: SodiumLightBulb
  parent: BaseLightRecipe

- type: latheRecipe
  id: ExteriorLightBulb
  result: ExteriorLightBulb
  parent: BaseLightRecipe

- type: latheRecipe
  id: DrinkIceBucketEmpty
  result: DrinkIceBucketEmpty
  parent: BaseServiceItemsRecipe
  completetime: 2
  materials:
    Steel: 100

- type: latheRecipe
  id: DeskBell
  result: DeskBell
  parent: BaseServiceItemsRecipe
  completetime: 2
  materials:
    Steel: 200

- type: latheRecipe
  id: BrbSign
  result: BrbSign
  parent: BaseServiceItemsRecipe
  materials:
    Cardboard: 200

- type: latheRecipe
  id: DrinkKegSteel
  name: lathe-recipe-DrinkKegSteel-name
  result: DrinkKegSteel
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: DrinkKegPlastic
  name: lathe-recipe-DrinkKegPlastic-name
  result: DrinkKegPlastic
  completetime: 2
  materials:
    Plastic: 300

- type: latheRecipe
  id: DrinkKegWood
  name: lathe-recipe-DrinkKegWood-name
  result: DrinkKegWood
  completetime: 2
  materials:
    Wood: 300

- type: latheRecipe
  id: FoodFrozenPopsicleTrash
  result: FoodFrozenPopsicleTrash # I know, it has 'trash' in the name, but it's used in cooking!
  completetime: 0.5
  materials:
    Wood: 25

- type: latheRecipe
  id: DrinkWaterCup
  result: DrinkWaterCup
  completetime: 0.5
  materials:
    Paper: 25

# Donk co Service Fab

- type: latheRecipe
  parent: BaseToolRecipe
  id: DrinkDonkcoCup
  result: DrinkDonkcoCup
  materials:
    Cardboard: 25

- type: latheRecipe
  parent: NFBaseBoxRecipe
  id: FoodBoxDonkngo
  result: FoodBoxDonkngo
  materials:
    Cardboard: 25

 - type: latheRecipe
 parent: NFBaseJumpsuitRecipe
 id: ClothingUniformJumpsuitDonkcoChef
 result: ClothingUniformJumpsuitDonkcoChef
 materials:
     Cloth: 100

 - type: latheRecipe
 parent: NFBaseCoatRecipe
 id: ClothingOuterDonkcoApron
 result: ClothingOuterDonkcoApron
 materials:
     Cloth: 100

 - type: latheRecipe
 parent: NFBaseHatRecipe
 id: ClothingHeadHatDonkcoHat
 result: ClothingHeadHatDonkcoHat
 materials:
     Cloth: 50

