- type: job
  id: Cadet
  name: job-name-cadet-nf
  description: job-description-cadet-nf
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # frontier = 6 hrs | CS = 12 hrs, TIME IN SECONDS
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3600 # frontier = 1 hr | CS = 6 hrs, TIME IN SECONDS
  startingGear: CadetGear
  icon: JobIconCadetNF
  supervisors: job-supervisors-cadet
  weight: 70
  displayWeight: 10
  canBeAntag: false
  accessGroups:
  - CadetNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddRpiJobModifierSpecial
    modifiersToAdd:
    - rpiJobModifierCadet

- type: startingGear
  id: CadetGear
  equipment:
    pocket1: NFWeaponPistolUniversalNfsdLessLethal
    pocket2: BookSecurity
  storage:
    back:
    - Flash
    - CSMagazinePistol40 # Coyote NFMagazineHighCapacityPistol35 < CSMagazinePistol40
    - CSMagazinePistol40Rubber # Coyote NFMagazineHighCapacityPistol35Rubber < CSMagazinePistol40Rubber
    - FrontierUplinkCoin10

- type: chameleonOutfit
  id: CadetChameleonOutfit
  job: Cadet
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterArmorNfsd
    neck: ClothingNeckNfsdBadgeSecurityCadet
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdBrown
    shoes: ClothingShoesBootsNfsdBrownFilled

